### ISSUE TITLE
Flaky UI test in CI

### ISSUE THREAD

**Issue by amenowanna** [mergestat/mergestat#615]
We appear to have a flaky test in the UI. This worked after re-running the job.

https://github.com/mergestat/mergestat/actions/runs/3609487739/jobs/6082710890

```      
      116 |     )
      117 |
    > 118 |     await waitFor(() => {
          |                  ^
      119 |       // Get input search to type
      120 |       const searchInput = screen.getByTestId(TEST_IDS.inputRepoSearch)
      121 |       if (searchInput) {

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:187:27)
      at Object.<anonymous> (src/__tests__/repos.test.tsx:118:18)

PASS src/__tests__/syncs.test.tsx (6.369 s)
PASS src/__tests__/settings.test.tsx

Test Suites: 1 failed, 3 passed, 4 total
Tests:       1 failed, 22 passed, 23 total
Snapshots:   0 total
Time:        20.169 s
Error: Process completed with exit code 1.
```

**Comment by patrickdevivo** [comment]
@german-mergestat the flaky test I see now is a bit different - not sure if we traded one for another 😅 

![Image](https://user-images.githubusercontent.com/57259/208527853-94658884-e812-470a-a7c8-16a4b3fa9172.png)

This one looks like a timeout - I wonder if we could bump that in the CI run to give us a bit more breathing room
