### ISSUE TITLE
Panic in GitHub Actions syncer

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#854]
![image](https://user-images.githubusercontent.com/57259/220202793-8653bf12-732a-4edc-9504-d58b1a3de975.png)

```
worker_1    | Feb 20 21:38:14 DBG getting workflow run log of ID=11476175194 job-type=GITHUB_ACTIONS repo=https://github.com/mergestat/mergestat workflow-job="CI Frontend (UI)"
worker_1    | panic: runtime error: invalid memory address or nil pointer dereference
worker_1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xacc90d]
worker_1    | 
worker_1    | goroutine 118 [running]:
worker_1    | github.com/mergestat/mergestat/internal/warehouse.(*warehouse).handleWorkflowJobUpsert(0xc0019fb800, {0x17d85d8, 0xc00013e040}, 0xc001a64000, {0xc0017f0000, 0x1ba}, {0xd6, 0xdd, 0x71, 0xaa, ...})
worker_1    |   /src/internal/warehouse/github_actions.go:504 +0x50d
worker_1    | github.com/mergestat/mergestat/internal/warehouse.(*warehouse).handleWorkflowJobLogs(0xc0019fb800, {0x17d85d8, 0xc00013e040}, {0xc0012ac2b3, 0x9}, {0xc0012ac2bd, 0x9}, {0xd6, 0xdd, 0x71, ...}, ...)
worker_1    |   /src/internal/warehouse/github_actions.go:348 +0x576
worker_1    | github.com/mergestat/mergestat/internal/warehouse.(*warehouse).handleWorkflowRunsJobs(0xc0019fb800, {0x17d85d8, 0xc00013e040}, {0xc0012ac2b3, 0x9}, {0xc0012ac2bd, 0x9}, 0xc0017aa200, {0xc001496160, 0x1e, ...}, ...)
worker_1    |   /src/internal/warehouse/github_actions.go:267 +0x349
worker_1    | github.com/mergestat/mergestat/internal/warehouse.(*warehouse).handleWorkflowRuns(0xc0019fb800, {0x17d85d8, 0xc00013e040}, {0xc0012ac2b3, 0x9}, {0xc0012ac2bd, 0x9}, 0xc0017aa200, {0xc0001fd3b0, 0xc, ...})
worker_1    |   /src/internal/warehouse/github_actions.go:187 +0x9dd
worker_1    | github.com/mergestat/mergestat/internal/warehouse.(*warehouse).handleWorkflows(0xc0019fb800, {0x17d85d8, 0xc00013e040}, {0xc0012ac2b3, 0x9}, {0xc0012ac2bd, 0x9}, 0xc0017aa200)
worker_1    |   /src/internal/warehouse/github_actions.go:96 +0x355
worker_1    | github.com/mergestat/mergestat/internal/warehouse.(*warehouse).GitHubActions(0xc0019fb800, {0x17d85d8, 0xc00013e040}, 0xc0017aa200)
worker_1    |   /src/internal/warehouse/github_actions.go:40 +0x165
worker_1    | github.com/mergestat/mergestat/internal/syncer.(*worker).handleGithubActions(0xc00117a8d0, {0x17d85d8, 0xc00013e040}, 0xc0017aa200)
worker_1    |   /src/internal/syncer/github_actions.go:34 +0x296
worker_1    | github.com/mergestat/mergestat/internal/syncer.(*worker).handle(0xc0012648a0?, {0x17d85d8, 0xc00013e040}, 0xc0017aa200)
worker_1    |   /src/internal/syncer/syncer.go:188 +0x339
worker_1    | github.com/mergestat/mergestat/internal/syncer.(*worker).exec(0xc00117a8d0, {0x17d85d8, 0xc00013e040}, {0x23a0f28, 0x1})
worker_1    |   /src/internal/syncer/syncer.go:118 +0x22c
worker_1    | github.com/mergestat/mergestat/internal/syncer.(*worker).Start.func1(0x0?)
worker_1    |   /src/internal/syncer/syncer.go:210 +0x90
worker_1    | created by github.com/mergestat/mergestat/internal/syncer.(*worker).Start
worker_1    |   /src/internal/syncer/syncer.go:209 +0x5d
```

**Comment by amenowanna** [comment]
closing as we are using container syncs now.
