### ISSUE TITLE
Panic in repo metadata/info syncer

### ISSUE THREAD

**Issue by amenowanna** [mergestat/mergestat#912]
The syncer is throwing this panic:

```
mergestat-worker
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc74005]

goroutine 74 [running]:
github.com/mergestat/mergestat/internal/syncer.(*worker).getRepositoryInfo(0xc000563dd0, {0x17f7818, 0xc001128700}, {0xc05408b440, 0x28}, {0xc017d2e160, 0x20})
	/src/internal/syncer/github_repo_metadata.go:269 +0x3c5
github.com/mergestat/mergestat/internal/syncer.(*worker).handleGitHubRepoMetadata(0xc000563dd0, {0x17f7818, 0xc001128700}, 0xc02d318690)
	/src/internal/syncer/github_repo_metadata.go:55 +0x3a7
github.com/mergestat/mergestat/internal/syncer.(*worker).handle(0xc01b469680?, {0x17f7818, 0xc001128700}, 0xc02d318690)
	/src/internal/syncer/syncer.go:175 +0x949
github.com/mergestat/mergestat/internal/syncer.(*worker).exec(0xc000563dd0, {0x17f7818, 0xc001128700}, {0x23ca110, 0x1})
	/src/internal/syncer/syncer.go:121 +0x22c
github.com/mergestat/mergestat/internal/syncer.(*worker).Start.func1(0x0?)
	/src/internal/syncer/syncer.go:213 +0x90
created by github.com/mergestat/mergestat/internal/syncer.(*worker).Start
	/src/internal/syncer/syncer.go:212 +0x5d
```

**Comment by amenowanna** [comment]
Going to take over this ticket for now and monitor now that we have increased the disk size for the pod.

**Comment by amenowanna** [comment]
closing as we have moved to container syncs
